[package]
name = "fbcsv"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]

[dependencies]
human-panic = "1.0.0"
failure = "0.1.1"
failure_derive = "0.1.1"
csv = "1.0.0"
serde_derive = "1.0"
serde = "1.0"
clap = "2.32.0"

